start_datetime: "2022-01-01"
vk:
#  login: "YOUR_VK_LOGIN"
#  password: YOUR_VK_PASSWORD
  access_token: "YOUR_ACCESS_TOKEN"
  v: "1.3"
db:
  host: localhost
  db_name: crawler_storage
  user_name: postgres
  password: YOUR_DATABASE_PASSWORD
queries:
  spbu:
    - spbu
    - спбгу
  msu:
    - msu
    - мгу
filter_words:
  spbu:
    - spbu
    - спбгу
    - санкт-петербургский государственный университет
  msu:
    - msu
    - мгу
    - московский государственный университет
